config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"
  devise_for :users
  # cards
  get "cards", to: "cards#index", as: "cards"
  get "cards/:card_id", to: "cards#show", as: "card"
  # listings
  get "listings", to: "listings#index", as: "listings"
  post "listings", to: "listings#create", as: "create_listing"
  get "listings/new/:card_id", to: "listings#new", as: "new_listing"
  get "listings/:listing_id", to: "listings#show", as: "listing"
  put "listings/:listing_id", to: "listings#update"
  patch "listings/:listing_id", to: "listings#update"
  delete "listings/:listing_id", to: "listings#destroy"
  get "listings/edit/:listing_id/:card_id", to: "listings#edit", as: "edit_listing" # requires listing_id and card_id incase of fail
  # profiles
  get "profiles/:id", to: "profiles#show", as: "profile"
  # favourites
  post "favourites", to: "favourites#create", as: "create_favourite"
  delete "favourites/:card_id", to: "favourites#destroy"
  # payments (stripe etc)
  get "payments/success/:id", to: "payments#success", as: "payment_success"
  get "payments/cancel/:id", to: "payments#cancel", as: "payment_cancel"
  post "payments/webhook", to: "payments#webhook"
  post "payments", to: "payments#create_checkout_session", as: "create_checkout_session"
end

app/models/card.rb
class Card < ApplicationRecord
  include ApplicationHelper # imports ApplicationHelper for card_prices method
  belongs_to :card_set
  has_many :listings
  
  before_save :remove_db_junk

  include PgSearch::Model # imports PgSearch library for PSQL searches
  pg_search_scope :search, against: [:name, :rarity, :card_set_id, :supertype],
                           associated_against: { card_set: :name }, # allow cross model search against card_set name in card_sets
                           using: { tsearch: { prefix: true } } # allows partial matches (LIKE)

  def self.text_search(query)
    if query.present?
      search(query) # search with query using pgsearch module method
    else
      Card.all # returns all cards if no match, order by card name
    end
  end

  private

  # sanitize data/reformat before saving into the database
  def remove_db_junk # isolate pokemon name, then remove trailing words if uncaught
    self.sprite_name = self.sprite_name.gsub(/Dark |Team Magma's |Team Aqua's |-EX|Erika's |Blaine's | FB| G| δ| Gl|Detective | V|Alolan |Brock's|Misty's |/i, "").strip
    self.evolves_from = self.evolves_from.to_s if !self.evolves_from.nil?

    if self.national_pokedex_number != nil
      self.national_pokedex_number = ("%03d" % "#{(self.national_pokedex_number.gsub(/"|\[|\]/, "")).to_i}")
    else
      self.national_pokedex_number = self.national_pokedex_number
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show]

  def index
    # pagy & card variable receive results of card model PgSearch method query
    # (params received from respective search form, and orederd by cards.name)
    @pagy, @cards = pagy(Card.text_search(params[:query]))
    if @cards.count == 0
      redirect_to root_path, alert: "😥 Couldn't find that card, try again"
    end
  end

  def show; end

  private

  def set_card # set the card, prices & relevant listings required for card overview
    begin
      @card = Card.find(params[:card_id]) # searches db for relevant card id matching params[:card_id]
      @prices = @card.card_prices(@card.id) # calls API price data using application_helper
    rescue
      redirect_to root_path, alert: "😥 Couldn't find that card, try again"
    end
    # set listings for the listings table (only store in @listings if not sold)
    # sort by created at, most recent populates to the top of the table
    # only reach this line if we don't throw an error in previous block
    @listings = Listing.where(card_id: @card.id, sold: false).order(created_at: :desc)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
  def format_condition(int)
    case int
    when 1
      "Poor"
    when 2
      "Good"
    when 3
      "Fair"
    when 4
      "Excellent"
    when 5
      "Mint"
    end
  end
end

app/views/cards/_card_details.html.erb
<section class="trading-card__details">
    <div class="row row-cols-sm-1 row-cols-md-2 m-0 ">
        <!-- main card image -->
        <div class="col-sm d-flex align-items-center p-card">
            <%= image_tag @card.large_image, alt: @card.name, class: "large-card", style: "max-width: 100%;" %>
        </div>
        <!--  main text body -->
        <!-- row 1 -->
        <div class="col-sm top">
            <!-- if rarity true -->
            <% if @card.rarity %> 
                <h2 class="text-center pb-2 body-heading"><%= @card.supertype %> 
                <!-- append subtypes if it exists -->
                <% if @card.subtypes %> 
                    — <%= purge_s_brackets(@card.subtypes) %>
                <% end %> 
                </h2> 
                <div class="row row-cols-2 m-0 pb-3">
                    <div class="col-sm">
                        <div class="row m-0">
                            <h2 class="card-name"><%= @card.name %></h2>
                        </div>
                        <div class="row m-0">
                            <h3 class="sub-heading"><%= @card.rarity %></h2>
                        </div>
                    </div>
                    <% if @prices.average_sell_price %>
                        <div class="col-sm">
                            <div class="row m-0">
                                <h3 class="font-weight-bold">Average</h3>
                            </div>
                            <div class="row m-0">
                                <h3>$ <%= ("%.2f" % @prices.average_sell_price) %></h3>
                            </div>
                        </div>
                    <% else %>
                        <div class="col-sm">
                            <div class="row m-0">
                                <h3 class="font-weight-bold">Average (Weekly)</h3>
                            </div>
                            <div class="row m-0">
                                <h3>$ <%= ("%.2f" % @prices.avg7) %></h3>
                            </div>
                        </div>
                    <% end %>
                </div>  
            <% else %>
            <!-- if rarity false -->
                <h2 class="text-center pb-2 body-heading"><%= @card.supertype %> — <%= purge_s_brackets(@card.subtypes) %></h2> 
                <div class="row row-cols-2 m-0 pb-3">
                    <div class="col-sm">
                        <div class="row m-0">
                            <h2 class="card-name"><%= @card.name %></h2>
                        </div>
                    </div>
                    <% if @prices.average_sell_price %>
                        <div class="col-sm">
                            <div class="row m-0">
                                <h3 class="font-weight-bold">Average</h3>
                            </div>
                            <div class="row m-0">
                                <h3>$ <%= ("%.2f" % @prices.average_sell_price) %></h3>
                            </div>
                        </div>
                    <% else %>
                        <div class="col-sm">
                            <div class="row m-0">
                                <h3 class="font-weight-bold">Average (Weekly)</h3>
                            </div>
                            <div class="row m-0">
                                <h3>$ <%= ("%.2f" % @prices.avg7) %></h3>
                            </div>
                        </div>
                    <% end %>
                </div> 
            <% end %>
            <!-- row 2 -->
            <% if @card.types %>
            <div class="row row-cols-2 m-0 pb-2">
                <div class="col-sm">
                    <div class="row m-0">
                        <p class="sub-heading">Type</p>
                    </div>
                    <div class="row m-0"><p><%= purge_s_brackets(@card.types) %></p></div>
                </div>
            </div>
            <% end %>
            <!-- Evolves to/form block -->
            <!-- row 3 -->
            <% if @card.evolves_from || @card.evolves_to %>
                <div class="row row-cols-2 m-0 pb-2">
                    <!-- evolves from? -->
                    <% if @card.evolves_from %>
                        <div class="col-sm justify-content-center">
                            <div class="row m-0">
                                <p class="sub-heading">Evolves from</p>
                            </div>
                            <div class="row m-0">
                                <%= remove_sprite_junk(@card.evolves_from) %>
                            </div>
                            <div class="row m-0">
                                <%= image_tag url_sm_sprite_ef(remove_sprite_junk(@card.evolves_from)), title: remove_sprite_junk(@card.evolves_from) %>
                            </div>
                        </div>
                    <% end %>
                    <!-- evolves to? -->
                    <% if @card.evolves_to %>
                        <div class="col-sm">
                            <div class="row m-0">
                                <p class="sub-heading">Evolves to</p>
                            </div>
                            <div class="row m-0">
                                <%= remove_sprite_junk(purge_s_brackets(@card.evolves_to)) %>
                            </div>
                            <div class="row m-0 ">
                                <%= image_tag url_sm_sprite_et(remove_sprite_junk(@card.evolves_to)), title: remove_sprite_junk(purge_s_brackets(@card.evolves_to)) %>
                            </div>
                        </div>
                    <% end %>
                </div>
            <% end %>
            <!-- additional info -->
            <!-- row 4 -->
            <% if @card.weaknesses || @card.resistances %>
            <div class="row row-cols-2 m-0 pb-2">
                <div class="col-sm">
                    <div class="row m-0">
                        <p class="sub-heading">Weakness</p>
                    </div>
                    <% if @card.weaknesses %>
                        <div class="row m-0">
                            <%= @card.weaknesses %>
                        </div>
                    <% else %>
                        <div class="row m-0">
                            N/A
                        </div>
                    <% end %>
                </div>
                <div class="col-sm">
                    <div class="row m-0 ">
                        <p class="sub-heading">Resistance</p>
                    </div>
                    <% if @card.resistances %>
                        <div class="row m-0 ">
                            <%= @card.resistances %>
                        </div>
                    <% else %>
                        <div class="row m-0 ">
                            None
                        </div>
                    <% end %>
                </div>
            </div>
            <% end %>
            <!-- rules section -->
            <!-- row 5 &/or 6 -->
            <% if @card.rules %>
            <div class="row m-0 pb-2">
                <div class="col-sm">
                    <div class="row m-0"><p class="sub-heading">Rules</p></div>
                    <div class="roww m-0"><%= @card.rules %></div>
                </div>
            </div> 
            <% end %>
            <!-- flavor text section -->
            <!-- row 5 &/or 6 -->
            <% if @card.flavor_text %>
            <div class="row m-0 pb-2">
                <div class="col-sm">
                    <p class="flavor-text"><i>"<%= @card.flavor_text %>"</i></p>
                </div>
            </div>
            <% end %>
            <div class="row text-center m-0 my-3 justify-content-center">
                <!-- checks if current user exists & if current user DOES NOT have a card favourite that matches the current card_id -->
                <% if current_user && !current_user.favourites.exists?(card_id: @card.id) %>
                    <div class="col d-flex justify-content-center ">
                    <!-- if user HAS NOT favourited the card -->
                    <%= button_to "♥",
                                  create_favourite_path,
                                  remote: true,
                                  method: :post,
                                  params: { card_id: @card.id },
                                  class: "fav btn btn-danger mb-3 text-center" %>
                    </div>
                <% else %> <!-- should display if no user and/or no card match between current card and favourited card_id -->
                    <div class="col d-flex justify-content-center ">
                        <!-- if the user has already favourited the card -->
                        <button class="fav btn btn-danger mb-3" disabled>♥</button>
                    </div>
                <% end %>
                <div class="col">
                    <%= button_to "Sell Now!",
                                  new_listing_path(@card.id),
                                  method: :get,
                                  class: "btn btn-info btn-lg p-1",
                                  style: "min-width:50%;width:80px;",
                                  data: { disable_with: "Loading..." } %>
                </div>
            </div>
            <div class="row row-cols-2 m-0 justify-content-center">
                <div class="set-symbol row justify-content-center w-100">
                    <div class="d-flex align-items-center"><%= image_tag "#{@card.card_set.symbol}", alt: "set-symbol", height: "30px", class: "pr-2" %></div>
                    <p class="set-text text-center"><i><%= "#{@card.card_set.card_set_id.upcase} (#{@card.number}/#{@card.card_set.printed_total})" %></i></p>
                </div>
            </div>               
        </div>
    </div>
</section>

app/views/cards/_large_listings.html.erb
<!-- large device table -->
<section class="listing-table listing-table--large mb-3">
    <table class="table table-striped m-0">
        <thead class="thead-dark">
            <tr>
                <th scope="col-sm">Seller Name</th>
                <th scope="col-sm">Price</th>
                <th scope="col-sm">Description</th>
                <th scope="col-sm">Condition</th>
                <th scope="col-sm" aria-label="buttons column header"> </th>
            </tr>
        </thead>
        <tbody>
            <% if @listings.present? %>
                <% @listings.each do |listing| %>
                    <tr>
                        <td scope="col-sm">
                            <div class="name-avatar d-flex justify-content-between">
                                <%= "#{listing.user.profile.first_name} #{listing.user.profile.last_name}" %>
                                <% if listing.user.avatar.attached? %>
                                    <%= image_tag listing.user.avatar_thumbnail, style: "margin-left:0.5rem;border-radius:5px;background:white;", size: "65x65", alt: "profile-avatar" if listing.user.avatar.attached? %>
                                <% else %>
                                    <%= image_tag "default-profile.jpg", style: "margin-left:0.5rem;border-radius:5px;", size: "65x65", alt: "profile-avatar" %>
                                <% end %>
                            </div>
                        </td>
                        <td scope="col-sm" style="width:100px;">$ <%= format_price(listing.price) %></td>
                        <td scope="col-sm"><%= listing.description %></td>
                        <td scope="col-sm" style="width:120px;font-weight:500;"><%= format_condition(listing.condition) %></td>
                        <td scope="col-sm" aria-label="buttons column body" style="width:120px;border-left: 1px solid #dee2e6;">
                            <!-- button posts listing to stripe webhook, allows us to create stripe session and create order -->
                            <%= button_to "Buy",
                                          create_checkout_session_path,
                                          remote: true,
                                          method: :post,
                                          params: { id: listing.id },
                                          class: "btn btn-primary",
                                          style: "min-width:100%;width:60px",
                                          data: { disable_with: "Loading..." } if current_user && current_user.id != listing.user_id %>
                            <%= button_to "View",
                                          listing_path(listing.id),
                                          method: :get,
                                          class: "btn btn-success mt-1",
                                          style: "min-width:100%;width:60px",
                                          data: { disable_with: "Loading..." } %> 
                                            <!-- override default post method to a get request -->
                            <% if current_user && current_user.id == listing.user_id %>
                                <%= button_to "Edit",
                                              edit_listing_path(listing_id: listing.id, card_id: @card.id),
                                              method: :get,
                                              class: "btn btn-warning mt-1",
                                              style: "min-width:100%;width:60px",
                                              data: { disable_with: "Loading..." } %>                         
                            <% end %>
                        </td>
                    </tr>
                <% end %>
            <% else %>
            <!-- render in an empty row when no listings for given card -->
                <tr>
                    <td colspan="5">
                        <div class="empty-row"><p class="text-center m-0">Nothing here yet, check back later!</p></div>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</section>

app/views/cards/_mobile_listings.html.erb
<!-- mobile table-->
<section class="listing-table listing-table--mobile mb-3">
    <table class="table table-striped m-0">
        <thead class="thead-dark">
            <tr>
                <th scope="col-sm">Seller Name</th>
                <th scope="col-sm">Price</th>
                <th scope="col-sm">Condition</th>
                <th scope="col-sm" aria-label="buttons column header"> </th>
            </tr>
        </thead>
        <tbody>
            <% if @listings.present? %>
                <% @listings.each do |listing| %>
                    <tr>
                        <td scope="col-sm"><%= "#{listing.user.profile.first_name} #{listing.user.profile.last_name}" %></td>
                        <td scope="col-sm">$<%= format_price(listing.price) %></td>
                        <td scope="col-sm" style="font-weight:500;"><%= format_condition(listing.condition) %></td>
                        <td scope="col-sm" style="border-left: 1px solid #dee2e6;">
                            <div>
                                <!-- button posts listing to stripe webhook, allows us to create stripe session and create order -->
                                <%= button_to "Buy",
                                              create_checkout_session_path,
                                              remote: true,
                                              method: :post,
                                              params: { id: listing.id },
                                              class: "btn btn-primary",
                                              style: "min-width:100%;width:80px;",
                                              data: { disable_with: "Loading..." } if current_user && current_user.id != listing.user_id %>
                                <%= button_to "View", listing_path(listing.id),
                                              method: :get,
                                              class: "btn btn-success mt-1",
                                              style: "min-width:100%;width:80px;",
                                              data: { disable_with: "Loading..." } %> 
                                              <!-- override default post method -->
                                <% if current_user && current_user.id == listing.user_id %>
                                    <%= button_to "Edit",
                                                  edit_listing_path(listing_id: listing.id, card_id: @card.id),
                                                  method: :get,
                                                  class: "btn btn-warning mt-1",
                                                  style: "min-width:100%;width:80px;" %> 
                                                  <!-- override default post method -->
                                <% end %>
                            </div>
                        </td>
                    </tr>
                    <% end %>
            <% else %><!-- render in an empty row when no listings for given card -->
                <tr>
                    <td colspan="4">
                        <div class="empty-row"><p class="text-center m-0">Nothing here yet, check back later!</p></div>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
</section>

app/views/cards/index.html.erb
<section class="index">
    <div class="index__pagination mt-2">
        <%== pagy_bootstrap_nav(@pagy, class: "pagy-nav") %> 
    </div>

    <div class="index__row row row-cols-2 row-cols-sm-2 row-cols-md-3 row-cols-lg-6">
        <% for card in @cards %> 
            <div class="index__row-card col d-flex justify-content-center">
                <div class="d-flex flex-column">
                    <a href="<%= card_path(card.id) %>">
                        <%= image_tag "#{card.small_image}", id: "#{dom_id(card)}", class: "card-img my-2", alt: "#{card.name} trading card" %>
                    </a>
                    <% if current_user %>
                        <div class="index__row-card-market-menu">
                            <%= link_to "Buy", card_path(card.id), class: "index__row-card-market-menu-buy" %>
                            <%= link_to "Sell", new_listing_path(card.id), class: "index__row-card-market-menu-sell" %>
                        </div>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
    
    <div class="index__pagination">
        <%== pagy_bootstrap_nav(@pagy, class: "pagy-nav") %> 
    </div>
</section>

app/views/cards/show.html.erb
<!-- encapsulates card_details & table element -->
<div class="trading-card d-flex flex-column align-items-center pt-3">
    <%= render "card_details" %> <!-- contains card details element -->
    <%= render "large_listings" %> <!-- rendered if large screen -->
    <%= render "mobile_listings" %> <!-- rendered if mobile screen -->
</div>